version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/schema-json-js
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/schema-json-js

  install_dependencies:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/schema-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install --no-optional
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/schema-json-js/node_modules

  test:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/schema-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run lint and unit tests
          command: npm run test:all && npm test
      - run:
          name: Run coverage report
          command: npm run coverage
      - store_test_results:
          path: ~/schema-json-js/coverage.lcov
      - store_artifacts:
          path: ~/schema-json-js/coverage.lcov

  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/schema-json-js
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build code
          command: npm run build

workflows:
  version: 2
  code-review:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - test
