version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/js-schema-json
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/js-schema-json

  install_dependencies:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/js-schema-json
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --no-optional
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/js-schema-json/node_modules

  test:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/js-schema-json
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Run lint and unit tests
          command: npm run test:all && npm test
      - run:
          name: Run coverage report
          command: npm run coverage
      - store_test_results:
          path: ~/js-schema-json/coverage.lcov
      - store_artifacts:
          path: ~/js-schema-json/coverage.lcov

  build:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/js-schema-json
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Build and compress code
          command: npm run build && node ./bin/compress
      - save_cache:
          key: assets-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/js-schema-json/package.tar.gz
      - store_artifacts:
          path: ~/js-schema-json/package.tar.gz

workflows:
  version: 2
  code-review:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - test
